package de.frank_rahn.xmlns.ws.echo._1_1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-18T21:07:39.084+02:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "EchoService", 
                  wsdlLocation = "http://xmlns.frank-rahn.de/ws/echo/1.1",
                  targetNamespace = "http://xmlns.frank-rahn.de/ws/echo/1.1") 
public class EchoService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.frank-rahn.de/ws/echo/1.1", "EchoService");
    public final static QName EchoServiceSoap = new QName("http://xmlns.frank-rahn.de/ws/echo/1.1", "EchoServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://xmlns.frank-rahn.de/ws/echo/1.1");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EchoService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://xmlns.frank-rahn.de/ws/echo/1.1");
        }
        WSDL_LOCATION = url;
    }

    public EchoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EchoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EchoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServiceSoap")
    public EchoService getEchoServiceSoap() {
        return super.getPort(EchoServiceSoap, EchoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServiceSoap")
    public EchoService getEchoServiceSoap(WebServiceFeature... features) {
        return super.getPort(EchoServiceSoap, EchoService.class, features);
    }

}
