
package de.frank_rahn.xmlns.ws.echo._1_1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-18T21:07:39.073+02:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "echoFault", targetNamespace = "http://xmlns.frank-rahn.de/services/echo/1.1")
public class EchoFault extends Exception {
    
    private de.frank_rahn.xmlns.types.error._1.ErrorFault echoFault;

    public EchoFault() {
        super();
    }
    
    public EchoFault(String message) {
        super(message);
    }
    
    public EchoFault(String message, Throwable cause) {
        super(message, cause);
    }

    public EchoFault(String message, de.frank_rahn.xmlns.types.error._1.ErrorFault echoFault) {
        super(message);
        this.echoFault = echoFault;
    }

    public EchoFault(String message, de.frank_rahn.xmlns.types.error._1.ErrorFault echoFault, Throwable cause) {
        super(message, cause);
        this.echoFault = echoFault;
    }

    public de.frank_rahn.xmlns.types.error._1.ErrorFault getFaultInfo() {
        return this.echoFault;
    }
}
