package de.frank_rahn.xmlns.ws.bic._1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-05-02T19:12:22.132+02:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://xmlns.frank-rahn.de/ws/bic/1.0", name = "BicService")
@XmlSeeAlso({de.frank_rahn.xmlns.services.bic._1.ObjectFactory.class, de.frank_rahn.xmlns.types.error._1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BicService {

    @WebResult(name = "bicResponse", targetNamespace = "http://xmlns.frank-rahn.de/services/bic/1.0", partName = "bicRequest")
    @WebMethod(action = "http://xmlns.frank-rahn.de/ws/bic/1.0/bic")
    public de.frank_rahn.xmlns.services.bic._1.BicResponse bic(
        @WebParam(partName = "bicRequest", name = "bicRequest", targetNamespace = "http://xmlns.frank-rahn.de/services/bic/1.0")
        de.frank_rahn.xmlns.services.bic._1.BicRequest bicRequest
    );
}
