package de.frank_rahn.xmlns.ws.bic._1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-05-02T19:12:22.162+02:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "BicService", 
                  wsdlLocation = "http://xmlns.frank-rahn.de/ws/bic/1.0",
                  targetNamespace = "http://xmlns.frank-rahn.de/ws/bic/1.0") 
public class BicService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.frank-rahn.de/ws/bic/1.0", "BicService");
    public final static QName BicServiceSoap = new QName("http://xmlns.frank-rahn.de/ws/bic/1.0", "BicServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://xmlns.frank-rahn.de/ws/bic/1.0");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BicService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://xmlns.frank-rahn.de/ws/bic/1.0");
        }
        WSDL_LOCATION = url;
    }

    public BicService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BicService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BicService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BicService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BicService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BicService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BicService
     */
    @WebEndpoint(name = "BicServiceSoap")
    public BicService getBicServiceSoap() {
        return super.getPort(BicServiceSoap, BicService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BicService
     */
    @WebEndpoint(name = "BicServiceSoap")
    public BicService getBicServiceSoap(WebServiceFeature... features) {
        return super.getPort(BicServiceSoap, BicService.class, features);
    }

}
