package de.rahn.legstar.cixs.bk010;
import org.mule.transformer.types.DataTypeFactory;
import org.mule.transport.legstar.transformer.AbstractHostToJavaMuleTransformer;
import de.frank_rahn.xmlns.types.cixs.cbk010.output._1.Dfhcommarea;
import de.frank_rahn.xmlns.types.cixs.cbk010.output._1.bind.DfhcommareaTransformers;

/**
 * Host Byte Array to Dfhcommarea Mule Transformer.
 * <p/>
 * <code>HostToDfhcommareaMuleTransformer</code> takes a byte array in host format
 * (EBCDIC) coming from a source Mainframe as input and turns it into
 * a Dfhcommarea object.
 * <p/>
 * Class generated by LegStar Mule Component generator.
 */
public class HostToDfhcommareaMuleTransformer extends AbstractHostToJavaMuleTransformer {

    /**
     * Constructs the transformer. Source is a byte array and result will be
     * a Dfhcommarea object.
     */
    public HostToDfhcommareaMuleTransformer() {
        super(new DfhcommareaTransformers());
        setReturnDataType(DataTypeFactory.create(Dfhcommarea.class));
    }


}
