package de.frank_rahn.xmlns.ws.echo._1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-04-18T21:07:37.321+02:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://xmlns.frank-rahn.de/ws/echo/1.0", name = "EchoService")
@XmlSeeAlso({de.frank_rahn.xmlns.services.echo._1.ObjectFactory.class, de.frank_rahn.xmlns.types.error._1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EchoService {

    @WebResult(name = "echoResponse", targetNamespace = "http://xmlns.frank-rahn.de/services/echo/1.0", partName = "echoRequest")
    @WebMethod(action = "http://xmlns.frank-rahn.de/ws/echo/1.0/echo")
    public de.frank_rahn.xmlns.services.echo._1.EchoResponse echo(
        @WebParam(partName = "echoRequest", name = "echoRequest", targetNamespace = "http://xmlns.frank-rahn.de/services/echo/1.0")
        de.frank_rahn.xmlns.services.echo._1.EchoRequest echoRequest
    ) throws EchoFault;
}
